[files]
extend-exclude = [
  "**/src/locales/",
  "patches/",
  "packages/utils/",
  "packages/ui/",
  "packages/blog/",
]

[default.extend-words]
# Terms Of Use in `tou-link`
tou = "tou"
# Google Ad Manager
gam = "gam"
# short for "constants"
consts = "consts"
# short for "Copy"
Cpy = "Cpy"

[default.extend-identifiers]
# Constant from the `zip` crate
ZIP64_BYTES_THR = "ZIP64_BYTES_THR"
